#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/wallet_test
#    username: root
#    password: dnjstjr11!
#
##    url: jdbc:mysql://10.0.76.17/wallet
##    username: myuser
##    password: mypassword

server:
  ssl:
    enabled: true
    key-store: classpath:superstrong-keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
  port: 8443

spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/wallet_test
    #    username: root
    #    password: dnjstjr11!

    url: jdbc:mysql://10.0.76.17/wallet
    username: myuser
    password: mypassword













